on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: borales/actions-yarn@master
        with:
          cmd: install --frozen-lockfile
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
